# Comparative analysis

This notebook only reads completed per-video summary artifacts. It never loads classifiers or reruns video analysis. Each workflow produces a validation table before comparisons. Explicit metadata (`video_path, group, treatment, animal, subject, region, well, day`) overrides folder-name inference. For treatment folders organized as `treatment/animal/video`, `animal` is inferred automatically from the parent folder.

In [21]:
from pathlib import Path
import sys

WORKING_DIR = Path.cwd().resolve()
PROJECT_ROOT = WORKING_DIR if (WORKING_DIR / 'gcamp_analysis').is_dir() else WORKING_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

from IPython.display import display
from gcamp_analysis.experiments.comparative import (
    run_hierarchical_comparison,
    run_longitudinal_comparison,
    run_treatment_comparison,
    save_comparison_tables,
)
from gcamp_analysis.reporting import save_comparisons

## Longitudinal groups

With `ALIGN=False`, this compares whole-video descriptive statistics across days and makes no cell-identity claim. `ALIGN=True` adds spatial registration, ROI matching, and cell/group tracking while retaining the descriptive tables.

In [15]:
LONGITUDINAL_GROUPS = {
    # 'region_1': Path(r'C:\\path\\to\\region_1'),
}
LONGITUDINAL_METADATA = None  # optional CSV/XLSX/Parquet path or DataFrame
ALIGN = False
LONGITUDINAL_OUTPUT = PROJECT_ROOT / 'comparison_outputs' / 'longitudinal'

In [16]:
longitudinal_result = None
if LONGITUDINAL_GROUPS:
    longitudinal_result = run_longitudinal_comparison(
        LONGITUDINAL_GROUPS,
        metadata=LONGITUDINAL_METADATA,
        align=ALIGN,
        output_dir=LONGITUDINAL_OUTPUT if ALIGN else None,
    )
    display(longitudinal_result.validation.to_frame())
    if not longitudinal_result.validation.has_errors:
        display(longitudinal_result.group_day_summary)
        save_comparison_tables(
            longitudinal_result.tables,
            LONGITUDINAL_OUTPUT / 'longitudinal_comparison.xlsx',
        )
else:
    print('Configure LONGITUDINAL_GROUPS to run this section.')

Configure LONGITUDINAL_GROUPS to run this section.

## Treatment groups

Set the independent experimental unit for the current experiment. Common choices are `well`, `region`, or `animal`. Longitudinal-within-treatment analysis is optional; alignment is only used when longitudinal analysis is enabled.

In [22]:
TREATMENT_GROUPS = {
    'TSP-ONC' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1",
    'TSP-CTRL' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1",
    'INS-ONC' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1",
    'INS-CTRL' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1",
    'ChABC-CTRL' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1",
    'ChABC-ONC' : r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_ONC_Cohort 1",
    # 'control': Path(r'C:\\path\\to\\control'),
    # 'drug': Path(r'C:\\path\\to\\drug'),
}
TREATMENT_METADATA = {
    'video': 'region',
    'video_parent' : 'drug-treatment',
    'video_grandparent': 'animal',
    'video_ancestor_3': 'injury-treatment',
}
REPLICATE_UNIT = 'region'  # well, region, animal, or another metadata column
LONGITUDINAL_WITHIN_TREATMENT = False
ALIGN_WITHIN_TREATMENT = False
TREATMENT_OUTPUT = PROJECT_ROOT / 'comparison_outputs' / 'treatments'

In [23]:
treatment_result = None
if TREATMENT_GROUPS:
    treatment_result = run_treatment_comparison(
        TREATMENT_GROUPS,
        replicate_unit=REPLICATE_UNIT,
        metadata=TREATMENT_METADATA,
        longitudinal=LONGITUDINAL_WITHIN_TREATMENT,
        align=ALIGN_WITHIN_TREATMENT,
        output_dir=TREATMENT_OUTPUT if ALIGN_WITHIN_TREATMENT else None,
    )
    display(treatment_result.validation.to_frame())
    if not treatment_result.validation.has_errors:
        display(treatment_result.treatment_summary)
        if LONGITUDINAL_WITHIN_TREATMENT:
            display(treatment_result.treatment_day_summary)
        save_comparison_tables(
            treatment_result.tables,
            TREATMENT_OUTPUT / 'treatment_comparison.xlsx',
        )
else:
    print('Configure TREATMENT_GROUPS to run this section.')

,severity,code,group,video_path,message
0,error,missing_video_path_column,,,Explicit metadata requires a video_path column.
1,error,missing_metadata,TSP-ONC,C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo...,Required metadata field 'region' is missing.
2,error,missing_metadata,TSP-ONC,C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo...,Required metadata field 'region' is missing.
3,error,missing_metadata,TSP-ONC,C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo...,Required metadata field 'region' is missing.
4,error,missing_metadata,TSP-ONC,C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo...,Required metadata field 'region' is missing.
...,...,...,...,...,...
100,warning,low_replicate_count,TSP-CTRL,,Treatment 'TSP-CTRL' has only 1 independent re...
101,warning,low_replicate_count,INS-ONC,,Treatment 'INS-ONC' has only 1 independent reg...
102,warning,low_replicate_count,INS-CTRL,,Treatment 'INS-CTRL' has only 1 independent re...
103,warning,low_replicate_count,ChABC-CTRL,,Treatment 'ChABC-CTRL' has only 1 independent ...
104,warning,low_replicate_count,ChABC-ONC,,Treatment 'ChABC-ONC' has only 1 independent r...

## Generic filesystem sibling comparisons

This retains the original arbitrary hierarchy behavior: immediate child folders are compared at every internal node, using persisted per-video summaries.

In [24]:
HIERARCHICAL_ROOT = Path(r"C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710")  # e.g. Path(r'C:\\path\\to\\experiment')

if HIERARCHICAL_ROOT is not None:
    hierarchy_result = run_hierarchical_comparison(HIERARCHICAL_ROOT)
    display(hierarchy_result.validation.to_frame())
    if not hierarchy_result.validation.has_errors and hierarchy_result.root is not None:
        save_comparisons(
            root=hierarchy_result.root,
            sibling_tables=hierarchy_result.sibling_tables,
        )
        for node_path, table in hierarchy_result.sibling_tables.items():
            print(f'\nNode: {node_path}')
            display(table)
else:
    print('Set HIERARCHICAL_ROOT to run generic sibling comparisons.')

Empty DataFrame
Columns: [severity, code, group, video_path, message]
Index: []

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,rise_slope_hz_within_grouped,rise_slope_hz_between_grouped,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,n_cells_ON_1_response(s),n_cells_ON_2_response(s)
0,DoD_ChABC_CTRL_Cohort 1,11,1,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DoD_ChABC_ONC_Cohort 1,2,0,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DoD_INS_CTRL_Cohort 1,21,9,0.111111,0.888889,1.0,1.0,1.0,0.0,4.000000,...,0.000590,0.000000,28.969210,24.829682,4.139528,0.000000,0.000000,0.000000,NaN,NaN
3,DoD_INS_ONC_Cohort 1,17,6,0.500000,0.500000,3.0,1.0,1.0,0.0,3.000000,...,0.002767,0.000012,0.027382,0.027382,0.000000,0.000147,0.000039,0.000108,1.000000,NaN
4,DoD_TSP-1_CTRL_Cohort 1,18,24,0.541667,0.458333,2.0,6.5,6.5,0.0,13.500000,...,0.003719,0.000000,19.283544,15.728915,3.554629,0.000391,0.000391,0.000000,6.500000,NaN
5,DoD_TSP-1_ONC_Cohort 1,29,44,0.477273,0.522727,6.0,3.5,3.5,0.0,8.833333,...,0.055343,0.000000,32.947912,32.736560,0.211352,0.000288,0.000288,0.000000,5.888889,2.333333

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5965,2,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5968,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5971,4,1,0.0,1.0,15.338245,0.069073,15.338245,0.069073,15.338245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5972,4,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1\5965

   child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0    BSA         1          0           0.0             0.0
1  ChABC         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1\5971

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,BSA,3,1,0.0,1.0,15.338245,0.069073,15.338245,0.069073,15.338245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ChABC,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1\5971\BSA

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5971Lepi-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5971Lepi-2,1,1,0.0,1.0,15.338245,0.069073,15.338245,0.069073,15.338245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5971Lepi-3,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_CTRL_Cohort 1\5972\BSA

        child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5972Repi-1         1          0           0.0             0.0
1  5972Repi-2         1          0           0.0             0.0
2  5972Repi-3         1          0           0.0             0.0
3  5972Repi-4         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_ChABC_ONC_Cohort 1

  child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5917         1          0           0.0             0.0
1  6124         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5975,2,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5976,1,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5978,2,4,0.25,0.75,1.0,1.0,1.0,0.0,4.0,...,0.000000,0.000155,0.000155,0.00000,0.0,0.0,0.0,0.000050,0.000050,0.00000
3,5980,11,5,0.00,1.00,0.0,0.0,0.0,0.0,0.0,...,0.000033,0.000132,0.000112,0.00002,NaN,NaN,NaN,0.000132,0.000112,0.00002
4,6046,4,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6099,1,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\5975\BSS

     child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5975L-1         1          0           0.0             0.0
1  5975L-2         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\5978\BSS

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5978L-1,1,4,1.0,1.0,1.0,0.0,4.0,0.25,0.75,...,0.000155,0.000155,0.0,0.000155,0.0,0.0,0.0,0.00005,0.0,0.00005
1,5978L-2,1,0,NaN,NaN,NaN,NaN,NaN,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\5980

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped,total_ON_cells,total_OFF_cells
0,BSS,2,2,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,0.0,0.000363,0.000363,0.0,0.000363,0.000363,0.0,0.000363,NaN,NaN
1,INS,9,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000056,0.000056,0.0,0.000056,0.000056,0.0,0.000056,0.0,0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\5980\BSS

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,spike_frequency_between_ungrouped,half_max_width_seconds_var_unweighted,half_max_width_seconds_within_unweighted,half_max_width_seconds_between_unweighted,half_max_width_seconds_var_weighted,half_max_width_seconds_within_weighted,half_max_width_seconds_between_weighted,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped
0,5980Lepi-1,1,1,0.0,1.0,10.456770,0.083996,10.456770,0.083996,10.456770,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5980Lepi-1repeat,1,1,0.0,1.0,8.195581,0.078415,8.195581,0.078415,8.195581,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\5980\INS

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5980Repi-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5980Repi-2,1,2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.000071,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5980Repi-2redo,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5980Repi-3,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5980Repi-3redo,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5980Repi-4,1,1,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,5980Repi-4redo,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5980Repi-5,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5980Repi-6,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_CTRL_Cohort 1\6046\INS

     child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  6046L-1         1          0           0.0             0.0
1  6046L-2         1          0           0.0             0.0
2  6046L-3         1          0           0.0             0.0
3  6046L-4         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped,n_cells_ON_3_response(s)
0,5534,4,3,1.0,1.0,1.0,0.0,4.0,0.333333,0.666667,...,0.000338,0.000338,0.0,0.000000,0.000000,0.0,0.000056,0.000056,0.0,NaN
1,5858,2,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5864,9,3,2.0,1.0,1.0,0.0,2.5,0.666667,0.333333,...,0.002372,0.002372,0.0,0.000056,0.000056,0.0,0.000000,0.000000,0.0,1.0
3,5868,2,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1\5534\INS

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5534L-1,1,2,1.0,1.0,1.0,0.0,4.0,0.5,0.5,...,0.000225,0.000225,0.0,0.000225,0.0,0.0,0.0,0.0,0.0,0.0
1,5534L-1redo,1,1,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,0.000000,0.000000,0.0,0.000000,NaN,NaN,NaN,0.0,0.0,0.0
2,5534L-2,1,0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5534L-3,1,0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1\5858\BSS

        child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0     5858L-1         1          0           0.0             0.0
1  5858Lepi-1         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1\5864\BSS

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,decay_tau_seconds_between_grouped,half_max_width_seconds_var_grouped,half_max_width_seconds_within_grouped,half_max_width_seconds_between_grouped,rise_slope_hz_var_grouped,rise_slope_hz_within_grouped,rise_slope_hz_between_grouped,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped
0,5864Repi-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5864Repi-2,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5864Repi-3,1,1,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5864Repi-3redo,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5864Repi-4,1,2,1.0,0.0,2.0,1.0,1.0,0.0,2.5,...,0.095979,0.0,0.0,0.0,0.002869,0.002863,0.000006,0.000056,0.0,0.000056
5,5864Repi-5,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5864Repi-6,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5864Repi-7,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,5864Repi-8,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_INS_ONC_Cohort 1\5868\INS

     child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5868R-1         1          0           0.0             0.0
1  5868R-2         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,decay_tau_seconds_between_grouped,half_max_width_seconds_var_grouped,half_max_width_seconds_within_grouped,half_max_width_seconds_between_grouped,rise_slope_hz_var_grouped,rise_slope_hz_within_grouped,rise_slope_hz_between_grouped,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped
0,5825,2,1,0.00,1.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5826,10,3,0.00,1.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5827,4,20,0.65,0.35,2.0,6.5,6.5,0.0,13.5,...,0.0,17.202728,17.202728,0.0,0.003719,0.003719,0.0,0.000391,0.000391,0.0
3,5829,2,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5825\BSS

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,half_max_width_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,half_max_width_seconds_mean_weighted,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5825R-1,1,1,0.0,1.0,5.658034,10.727322,0.119587,5.658034,10.727322,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5825R-2,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5826

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,half_max_width_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,half_max_width_seconds_mean_weighted,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,BSS,8,2,0.0,1.0,11.251567,17.800250,0.102258,11.251567,17.800250,...,0.000315,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TSP-1,2,1,0.0,1.0,6.091028,10.566747,0.071911,6.091028,10.566747,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5826\BSS

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,spike_frequency_between_ungrouped,half_max_width_seconds_var_unweighted,half_max_width_seconds_within_unweighted,half_max_width_seconds_between_unweighted,half_max_width_seconds_var_weighted,half_max_width_seconds_within_weighted,half_max_width_seconds_between_weighted,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped
0,5826L-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5826L-2,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5826L-3,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5826L-4,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5826L-5,1,1,0.0,1.0,13.912459,0.120008,13.912459,0.120008,13.912459,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5826L-6,1,1,0.0,1.0,8.590674,0.084508,8.590674,0.084508,8.590674,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,5826L-7,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,5826L-8,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5826\TSP-1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,half_max_width_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,half_max_width_seconds_mean_weighted,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5826R-1,1,1,0.0,1.0,6.091028,10.566747,0.071911,6.091028,10.566747,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,5826R-2,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5827\TSP-1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,...,half_max_width_seconds_between_grouped,rise_slope_hz_var_grouped,rise_slope_hz_within_grouped,rise_slope_hz_between_grouped,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped
0,5827L-1,1,1,0.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5827L-2,1,15,0.6,0.4,1.0,9.0,9.0,0.0,17.0,...,9.424160,0.000953,0.000415,0.000538,41.98623,40.549676,1.436553,0.000122,0.0,0.000122
2,5827L-2redo,1,4,1.0,0.0,1.0,4.0,4.0,0.0,10.0,...,24.961154,0.006477,0.004536,0.001940,NaN,NaN,NaN,0.000619,0.0,0.000619
3,5827L-3,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_CTRL_Cohort 1\5829\TSP-1

        child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5829Lepi-1         1          0           0.0             0.0
1  5829Lepi-2         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5834,11,36,6.0,3.5,3.5,0.0,8.833333,0.583333,0.416667,...,0.000612,0.002049,0.001442,0.000607,0.000288,0.000287,3.374656e-07,0.002250,0.001710,0.000540
1,5835,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5836,6,5,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,...,0.000014,0.000050,0.000037,0.000013,NaN,NaN,NaN,0.000050,0.000037,0.000013
3,5837,4,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5839,4,1,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000
5,5840,1,2,0.0,0.0,0.0,0.0,0.000000,0.000000,1.000000,...,0.000000,0.000056,0.000056,0.000000,NaN,NaN,NaN,0.000056,0.000056,0.000000
6,6040,2,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5834

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,BSS,6,32,4,4.75,4.75,0.0,12.0,0.59375,0.40625,...,0.000026,0.000160,0.000133,0.000026,0.000105,0.000035,0.00007,0.000135,0.000129,0.000006
1,TSP-1,5,4,2,1.00,1.00,0.0,2.5,0.50000,0.50000,...,0.002756,0.002981,0.000225,0.002756,0.000506,0.000506,0.00000,0.003600,0.000000,0.003600

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5834\BSS

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped,n_cells_ON_1_response(s)
0,5834L-1,1,7,1.0,3.0,3.0,0.0,10.0,0.428571,0.571429,...,0.000312,0.0,0.000312,0.000050,0.0,0.000050,0.000337,0.0,0.000337,NaN
1,5834L-2,1,21,2.0,7.5,7.5,0.0,18.0,0.714286,0.285714,...,0.000046,0.0,0.000046,0.000054,0.0,0.000054,0.000000,0.0,0.000000,12.0
2,5834L-3,1,4,1.0,1.0,1.0,0.0,2.0,0.250000,0.750000,...,0.000042,0.0,0.000042,0.000000,0.0,0.000000,0.000050,0.0,0.000050,1.0
3,5834L-4,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5834L-5,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5834L-6 epi,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5834\TSP-1

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_weighted,spike_frequency_var_grouped,spike_frequency_within_grouped,spike_frequency_between_grouped,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped
0,5834R-1 epi,1,3,2.0,1.0,1.0,0.0,2.5,0.666667,0.333333,...,0.00045,0.000506,0.0,0.000506,0.0,0.0,0.0,NaN,NaN,NaN
1,5834R-2 epi,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5834R-3 epi,1,1,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,...,0.00000,NaN,NaN,NaN,0.0,0.0,0.0,13.491663,13.491663,0.0
3,5834R-4 epi,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5834R-5 epi,1,0,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5836

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,BSS,4,4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.000386,0.000056,0.000019,0.000037,0.000056,0.000019,0.000037,0.000056,0.000019,0.000037
1,TSP-1,2,1,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5836\BSS

,child,n_videos,n_neurons,n_groups_light-evoked,mean_group_size_light-evoked,median_group_size_light-evoked,mean_group_corr_light-evoked,mean_spikes_per_group_light-evoked,frac_grouped,frac_ungrouped,...,spike_frequency_between_ungrouped,half_max_width_seconds_var_unweighted,half_max_width_seconds_within_unweighted,half_max_width_seconds_between_unweighted,half_max_width_seconds_var_weighted,half_max_width_seconds_within_weighted,half_max_width_seconds_between_weighted,half_max_width_seconds_var_ungrouped,half_max_width_seconds_within_ungrouped,half_max_width_seconds_between_ungrouped
0,5836R-1,1,2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.000056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5836R-2,1,1,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5836R-3,1,1,NaN,NaN,NaN,NaN,NaN,0.0,1.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5836R-4,1,0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5836\TSP-1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,half_max_width_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,half_max_width_seconds_mean_weighted,rise_slope_hz_mean_weighted,half_max_width_seconds_mean_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5836L-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5836L-2,1,1,0.0,1.0,13.440082,0.083283,13.440082,0.083283,13.440082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5837

   child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0    BSS         1          0           0.0             0.0
1  TSP-1         3          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5837\TSP-1

     child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  5837L-1         1          0           0.0             0.0
1  5837L-2         1          0           0.0             0.0
2  5837L-3         1          0           0.0             0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\5839\TSP-1

,child,n_videos,n_neurons,frac_grouped,frac_ungrouped,decay_tau_seconds_mean_unweighted,rise_slope_hz_mean_unweighted,decay_tau_seconds_mean_weighted,rise_slope_hz_mean_weighted,decay_tau_seconds_mean_ungrouped,...,rise_slope_hz_between_ungrouped,spike_frequency_var_unweighted,spike_frequency_within_unweighted,spike_frequency_between_unweighted,spike_frequency_var_weighted,spike_frequency_within_weighted,spike_frequency_between_weighted,spike_frequency_var_ungrouped,spike_frequency_within_ungrouped,spike_frequency_between_ungrouped
0,5839R-1,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5839R-2,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5839R-3,1,0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5839R-4,1,1,0.0,1.0,4.881297,0.128357,4.881297,0.128357,4.881297,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Node: C:\Users\mzinn1\Desktop\DoD WT Cohorts\Ex Vivo Ca Imaging 710\DoD_TSP-1_ONC_Cohort 1\6040\TSP-1

     child  n_videos  n_neurons  frac_grouped  frac_ungrouped
0  6040R-1         1          0           0.0             0.0
1  6040R-2         1          0           0.0             0.0